services:
  fleet-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fleet-sql
      - fleet-rabbitmq
      - fleet-redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=fleet-sql;Database=FleetTelemetryDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - RabbitMq__Host=fleet-rabbitmq
      - Redis__ConnectionString=fleet-redis:6379

  fleet-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1434:1433"
    volumes:
      - fleet-sql-data:/var/opt/mssql

  fleet-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      
  fleet-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  fleet-sql-data:
