services:
  fleet-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fleet-sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=fleet-sql;Database=FleetTelemetryDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True

  fleet-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1434:1433"